---
agent_list:
- <agent-private-ip-1>
- <agent-private-ip-2>
- <agent-private-ip-3>
- <agent-private-ip-4>
- <agent-private-ip-5>
# Use this bootstrap_url value unless you have moved the DC/OS installer assets.
bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: <cluster-name>
exhibitor_storage_backend: static
master_discovery: static
master_list:
- <master-private-ip-1>
- <master-private-ip-2>
- <master-private-ip-3>
public_agent_list:
- <public-agent-private-ip>
resolvers:
- 8.8.4.4
- 8.8.8.8
ssh_port: 22
ssh_user: root
enable_docker_gc: 'true'
ip_detect_public_filename: 'ipdetect-public'
oauth_enabled: 'false'
process_timeout: 12000
